apiVersion: v1
kind: Service
metadata:
  name: my-flask-app
  labels:
    app: my-flask-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: my-flask-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
  labels:
    app: my-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-flask-app
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
        version: "v0.0.1"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: my-flask-app
        image: nirmalpathak/sample-flask-prometheus-app
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5000
        env:
        - name: VERSION
          value: "v0.0.1"
